version: 2.1
orbs:
aws-ecr: circleci/aws-ecr@6.1.0
aws-ecs: circleci/aws-ecs@0.0.8
workflows:
build_and_push_image:
jobs:
- aws-ecr/build-and-push-image:
region: AWS_REGION
account-url: AWS_ECR_ACCOUNT_URL
repo: 'circleci'　# GitHubのリポジトリ名
tag: "${CIRCLE_SHA1}"
- aws-ecs/deploy-service-update:
requires:
- aws-ecr/build-and-push-image
family: 'mmtask'　# ECSのタスク定義名
cluster-name: 'mmCluster'　# ECSクラスター名
service-name: 'mmsvc'　# ECSのサービス名
container-image-name-updates: 'mmrepo,tag=${CIRCLE_SHA1}'　# タスク定義で指定しているコンテナ名
